### PR TITLE
Adding pin lock encryption.

### PR DESCRIPTION
**Pull request by pedro-arruda-moreira**
Hi. Added AES-256 encryption to the local storage for the pin lock on the PWA.

If you guys have a better suggestion for the encryption, tell me and I will change it.

thanks!

### CODE REVIEW

**Comment by hmil** [comment]
Great 👍 

I wrote a bit about this feature in #232. Basically, the problem was that a 4-digit pin is really easy to bruteforce. Hence, encrypting this data doesn't significantly increase the security of the app because an attacker can bruteforce the cipher in little time.

The only marginal benefit would be that if someone finds the stored blob and doesn't know what it is, then we don't leak any obvious clue as to what it is. However, if an attacker gets the stored blob with the intent to break it, then a simple offline bruteforce attack on the 4 digit pin would be effective.

So I'm OK with adding this feature if it doesn't do more harm than good. In this instance, you added two new dependencies in the project. As a matter of fact, the weakest point in this entire project is the dependency supply chain. It is well known that npm can be used as an attack vector to inject malware (cf. left-pad fiasco and similar stories). Hence, I think the number 1 priority should be to avoid adding new dependencies.

In brief: The cost of adding new library dependencies might outweigh the marginal security benefits offered by this feature.

Why not use sjcl.js from vaultage-client? This is a trusted crypto library which we have previously audited and committed into this repository to make sure it never gets tampered. It is best to only rely on that library whenever possible instead of importing new libraries from npm.

**Comment by pedro-arruda-moreira** [comment]
Good point. I will change the code to use sjcl.js.

**Comment by pedro-arruda-moreira** [comment]
Ok, changed to SJCL.

**Comment by hmil** [comment]
Great, thank you! 👏

**Pull request merged**
